stages:
  - deploy

deploy_production:
  stage: deploy
  script:
    - git checkout development
    - git pull origin development
    - rm /var/www/staging-dexa-web/*
    - cp -r * /var/www/staging-dexa-web/
  tags:
    - development
